window.VAPPIE_SEED = {
  "activeYear": "2026",
  "years": {
    "2026": {
      "rate": 6.5,
      "associations": [
        {
          "id": "a001",
          "name": "Actie JHB",
          "barchef": "Djamilla Giesen",
          "email": "actie@jhbblerick.nl",
          "phone": "",
          "planningName": "Actie JHB",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a002",
          "name": "Buurtvereniging De Boener",
          "barchef": "Frank Houben",
          "email": "frankh29@hotmail.com",
          "phone": "0655500263",
          "planningName": "Boener",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a003",
          "name": "CCB",
          "barchef": "Roy Hendrix",
          "email": "r.hendrix@cas.nl",
          "phone": "0645330993",
          "planningName": "CCB",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a004",
          "name": "Volleybalvereniging Civitas Venlo",
          "barchef": "Maik Tervooren",
          "email": "tervooren.m@gmail.com",
          "phone": "0640960882",
          "planningName": "Civitas",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a005",
          "name": "Concordia Wanssum",
          "barchef": "Fabienne Kremers",
          "email": "fabienne.kremers@gmail.com",
          "phone": "0646697298",
          "planningName": "Concordia",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a006",
          "name": "DCT",
          "barchef": "Ron Stultiens",
          "email": "rstultiens@home.nl",
          "phone": "0681429909",
          "planningName": "DCT",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a007",
          "name": "De Kwas",
          "barchef": "Harold Canters",
          "email": "Haroldcanters@ziggo.nl",
          "phone": "0621242653",
          "planningName": "De Kwas",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a008",
          "name": "VG De Törvers",
          "barchef": "Heini Derijk",
          "email": "hwderijk@home.nl",
          "phone": "0622808464",
          "planningName": "De Törvers",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a009",
          "name": "v.v. De Wien",
          "barchef": "Ron Janssen",
          "email": "ronjj66@gmail.com",
          "phone": "0641120412",
          "planningName": "De Wien",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a010",
          "name": "Delta H1",
          "barchef": "Joost Cornet",
          "email": "j.cornet@groenveldadviseurs.nl",
          "phone": "0629005263",
          "planningName": "Delta H1",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a011",
          "name": "HC Delta Venlo",
          "barchef": "Petra Denessen",
          "email": "P.denessen@gmail.com",
          "phone": "0610858256",
          "planningName": "Delta HC Dames1",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a012",
          "name": "Delta Venlo - team Winterberg",
          "barchef": "Simone Schouwenberg",
          "email": "jschouwenberg@ziggo.nl",
          "phone": "0651750925",
          "planningName": "Delta Winterberg",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a013",
          "name": "DWAC",
          "barchef": "Mart Gielen",
          "email": "m65art@hetnet.nl",
          "phone": "0653803659",
          "planningName": "DWAC",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a014",
          "name": "D'n Ellefde Man",
          "barchef": "Job van Lare",
          "email": "jobvanlare@hotmail.com",
          "phone": "0628243939",
          "planningName": "ellefde man",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a015",
          "name": "Familie Staeves",
          "barchef": "Willeke Stevens",
          "email": "willekestevens@zomerparkfeest.nl",
          "phone": "0618733450",
          "planningName": "Fam Stevens",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a016",
          "name": "Femilie Schreurs",
          "barchef": "Tim Schreurs",
          "email": "t.schreurs@hccnet.nl",
          "phone": "0648810793",
          "planningName": "Femilie Schreurs",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a017",
          "name": "Harmonie",
          "barchef": "Auke Fekkes",
          "email": "a.fekkes@gmx.de",
          "phone": "0651633842",
          "planningName": "Harmonie",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a018",
          "name": "Theaterkoor High Heels",
          "barchef": "Evelien Janssens Bartels",
          "email": "Straelseweg@hotmail.com",
          "phone": "0611032861",
          "planningName": "High Heels",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a019",
          "name": "Boereraod Tegelen Jeugd",
          "barchef": "Natasja Didden",
          "email": "diddennatasja@gmail.com",
          "phone": "0638456799",
          "planningName": "Jeug Boereraod",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a020",
          "name": "De Kwante Kaketoe",
          "barchef": "Jil Seelen",
          "email": "jilseelen@icloud.com",
          "phone": "0650860273",
          "planningName": "Kwante Kaketoe",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a021",
          "name": "NUATH",
          "barchef": "Lucas Peeters",
          "email": "Lucaspeeters@ziggo.nl",
          "phone": "0642440906",
          "planningName": "NUATH",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a022",
          "name": "BC Olympia'56",
          "barchef": "Joyce Steegh",
          "email": "secretariaat@bcolympia56.nl",
          "phone": "0614635799",
          "planningName": "Olympia",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a023",
          "name": "Oud bestuur",
          "barchef": "Anke Rutten",
          "email": "Ankerutten@zomerparkfeest.nl",
          "phone": "0648360082",
          "planningName": "Oud bestuur",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": 0
        },
        {
          "id": "a024",
          "name": "PRO Venlo",
          "barchef": "Hans Linssen",
          "email": "hansjlinssen@gmail.com",
          "phone": "0629594403",
          "planningName": "PRO Venlo",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a025",
          "name": "BC Rapido",
          "barchef": "Jeannine Huijbregts",
          "email": "wiljeannine@gmail.com",
          "phone": "0650218091",
          "planningName": "Rapido",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a026",
          "name": "St Jan Merselo rijvereniging en ponyclub",
          "barchef": "Pieter Verrijdt",
          "email": "Pieterverrijdt75@gmail.com",
          "phone": "0652673059",
          "planningName": "Rijvereniging st jan",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a027",
          "name": "Rockkoor Rock in Rooy",
          "barchef": "John Jansen",
          "email": "john@jansen-advies.com",
          "phone": "0618873868",
          "planningName": "Rock in Rooy",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a028",
          "name": "Roy’s gym/ Stichting Tiger Throwdown",
          "barchef": "Vivian Muris",
          "email": "murisv@hotmail.com",
          "phone": "0654738166",
          "planningName": "Roy's Gym",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a029",
          "name": "Schöd um Laeg",
          "barchef": "Jan van Nies",
          "email": "schodumlaegvenlo@gmail.com",
          "phone": "0635637922",
          "planningName": "Schöd um Laeg",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a030",
          "name": "Joekskepèl Schots en Scheif",
          "barchef": "Roel Venninckx",
          "email": "Roel@steijnbers.nl",
          "phone": "0621897083",
          "planningName": "Schots en Scheif",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a031",
          "name": "Scoutingbar gezamenlijk",
          "barchef": "Peter van Aken",
          "email": "Barchefs@scoutingblerick.nl",
          "phone": "0620259905",
          "planningName": "Scouting",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a032",
          "name": "Scouting Belfeld.",
          "barchef": "Remco Bonnen",
          "email": "Remco.boonen@scoutingbelfeld.nl",
          "phone": "0657782460",
          "planningName": "Scouting Belfeld",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a033",
          "name": "Stichting Sidera Theaterproducties",
          "barchef": "Kelly Hendrix",
          "email": "info@sideratheaterproducties.nl",
          "phone": "0611472072",
          "planningName": "Sidera",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a034",
          "name": "Stamtaofel Sintermerte",
          "barchef": "Richard Hovens",
          "email": "rhovens75@gmail.com",
          "phone": "0634097531",
          "planningName": "Stg Sintermerte",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a035",
          "name": "Vrindeklup TiedZat",
          "barchef": "Sander Kuilman",
          "email": "sanderkuilman@gmail.com",
          "phone": "0650749347",
          "planningName": "Tied zat",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a036",
          "name": "Ut Tuinhuuske",
          "barchef": "Huub Peters",
          "email": "hhtpeters@home.nl",
          "phone": "0654974010",
          "planningName": "Tuinhuuske",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a037",
          "name": "Muziekvereniging Valuas",
          "barchef": "Thea Vranken",
          "email": "ac@mvvaluas.nl",
          "phone": "0628083633",
          "planningName": "Valuas",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a038",
          "name": "VC Velden D1",
          "barchef": "Eke Denessen",
          "email": "ekedenessen@gmail.com",
          "phone": "0641129166",
          "planningName": "VC Velden D1",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a039",
          "name": "Venlose Revue",
          "barchef": "Francien Pollux",
          "email": "francien.pollux@gmail.com",
          "phone": "0618136925",
          "planningName": "Venloose revue",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a040",
          "name": "VG Beejeingesjoeid",
          "barchef": "Gido Mooren",
          "email": "gidomooren94@hotmail.com",
          "phone": "0683222815",
          "planningName": "VG Beejeingesjoeid",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a041",
          "name": "VG Noëit Beejein",
          "barchef": "Jeroen Hendrikx",
          "email": "jjphendrikx@gmail.com",
          "phone": "0657599200",
          "planningName": "VG Noëit Beejein",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a042",
          "name": "Vocaal Ensemble Quint",
          "barchef": "Jacqueline Sanders",
          "email": "jacqueline.jsa@gmail.com",
          "phone": "0648328566",
          "planningName": "Vocal Quint",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a043",
          "name": "Stichting Vrienden van Lotus",
          "barchef": "Thea van Bavel",
          "email": "wtvanbavel@gmail.com",
          "phone": "0648469012",
          "planningName": "Vrienden van Lotus",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a044",
          "name": "Vrijwilligersbar",
          "barchef": "Peter Paul Selen",
          "email": "info@ppservice.nl",
          "phone": "0622197131",
          "planningName": "Vrijwilligers",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": 0
        },
        {
          "id": "a045",
          "name": "VTC Casino",
          "barchef": "Jacqueline Receveur",
          "email": "mjreceveur@outlook.com",
          "phone": "0682754947",
          "planningName": "VTC Casino",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a046",
          "name": "Zwemvereniging De Watervrienden Venlo",
          "barchef": "Patrick Cromheecke",
          "email": "patrickcromheecke@gmail.com",
          "phone": "0655797772",
          "planningName": "Watervrienden",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a047",
          "name": "WBG Boeit neet",
          "barchef": "Gemma Oirbans",
          "email": "Gemma_Oirbans@hotmail.com",
          "phone": "0649644169",
          "planningName": "WBG Boeit neet",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a048",
          "name": "VG De Wortelepin",
          "barchef": "Ivo Fieten",
          "email": "ivofieten@gmail.com",
          "phone": "0653711702",
          "planningName": "Wortelepin",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a049",
          "name": "Worteleschrabbers",
          "barchef": "Tim verstegen",
          "email": "secretariaat@worteleschrabbers.nl",
          "phone": "0646452608",
          "planningName": "Worteleschrabbers",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Nee",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        },
        {
          "id": "a050",
          "name": "PSV Zeldenrust",
          "barchef": "Lisette Smits",
          "email": "lisettesmits@hotmail.com",
          "phone": "0625372687",
          "planningName": "Zeldenrust",
          "meeting1": "Onbekend",
          "meeting2": "Onbekend",
          "certificates": "Ja",
          "wristbands": "Nee",
          "shirts": "Ja",
          "mealVouchers": "Geen",
          "notes": "",
          "rateOverride": null
        }
      ],
      "shifts": [
        {
          "id": "s001",
          "associationId": "a003",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Wijnbar 1",
          "people": 4
        },
        {
          "id": "s002",
          "associationId": "a004",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Sp Bier bar 2",
          "people": 18
        },
        {
          "id": "s003",
          "associationId": "a014",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 8",
          "people": 12
        },
        {
          "id": "s004",
          "associationId": "a025",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Sp Bier Bar 1",
          "people": 15
        },
        {
          "id": "s005",
          "associationId": "a027",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 7",
          "people": 15
        },
        {
          "id": "s006",
          "associationId": "a031",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 4",
          "people": 40
        },
        {
          "id": "s007",
          "associationId": "a036",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 5",
          "people": 18
        },
        {
          "id": "s008",
          "associationId": "a037",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Cocktail 1",
          "people": 6
        },
        {
          "id": "s009",
          "associationId": "a043",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Cocktail 2",
          "people": 8
        },
        {
          "id": "s010",
          "associationId": "a044",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 2 (Vrijwilligersbar)",
          "people": 15
        },
        {
          "id": "s011",
          "associationId": "a048",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 6",
          "people": 18
        },
        {
          "id": "s012",
          "associationId": "a049",
          "day": "Donderdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 3 (Borrelbar)",
          "people": 15
        },
        {
          "id": "s013",
          "associationId": "a004",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Sp Bier bar 2",
          "people": 18
        },
        {
          "id": "s014",
          "associationId": "a009",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 5",
          "people": 18
        },
        {
          "id": "s015",
          "associationId": "a012",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Wijnbar 1",
          "people": 4
        },
        {
          "id": "s016",
          "associationId": "a021",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 6",
          "people": 10
        },
        {
          "id": "s017",
          "associationId": "a042",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 6",
          "people": 7
        },
        {
          "id": "s018",
          "associationId": "a025",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Sp Bier Bar 1",
          "people": 15
        },
        {
          "id": "s019",
          "associationId": "a031",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 4",
          "people": 40
        },
        {
          "id": "s020",
          "associationId": "a034",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 7",
          "people": 15
        },
        {
          "id": "s021",
          "associationId": "a035",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 8",
          "people": 12
        },
        {
          "id": "s022",
          "associationId": "a037",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Cocktail 1",
          "people": 6
        },
        {
          "id": "s023",
          "associationId": "a039",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 3 (Borrelbar)",
          "people": 15
        },
        {
          "id": "s024",
          "associationId": "a040",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Cocktail 2",
          "people": 6
        },
        {
          "id": "s025",
          "associationId": "a044",
          "day": "Vrijdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 2 (Vrijwilligersbar)",
          "people": 15
        },
        {
          "id": "s026",
          "associationId": "a004",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Sp Bier bar 2",
          "people": 18
        },
        {
          "id": "s027",
          "associationId": "a006",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Bar 3 (Borrelbar)",
          "people": 15
        },
        {
          "id": "s028",
          "associationId": "a009",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "13:30",
          "to": "18:00",
          "bar": "Bar 5",
          "people": 15
        },
        {
          "id": "s029",
          "associationId": "a012",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Wijnbar 1",
          "people": 4
        },
        {
          "id": "s030",
          "associationId": "a013",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Cocktail 2",
          "people": 6
        },
        {
          "id": "s031",
          "associationId": "a018",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Bar 8",
          "people": 6
        },
        {
          "id": "s032",
          "associationId": "a023",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 6",
          "people": 15
        },
        {
          "id": "s033",
          "associationId": "a025",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Sp Bier Bar 1",
          "people": 15
        },
        {
          "id": "s034",
          "associationId": "a031",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Bar 4",
          "people": 40
        },
        {
          "id": "s035",
          "associationId": "a035",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Bar 8",
          "people": 4
        },
        {
          "id": "s036",
          "associationId": "a037",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "14:30",
          "to": "18:00",
          "bar": "Cocktail 1",
          "people": 6
        },
        {
          "id": "s037",
          "associationId": "a039",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 7",
          "people": 9
        },
        {
          "id": "s038",
          "associationId": "a044",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 2 (Vrijwilligersbar)",
          "people": 15
        },
        {
          "id": "s039",
          "associationId": "a047",
          "day": "Vrijdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 7",
          "people": 5
        },
        {
          "id": "s041",
          "associationId": "a004",
          "day": "Woensdag",
          "daypart": "Avond",
          "from": "19:00",
          "to": "00:00",
          "bar": "Bar 6",
          "people": 18
        },
        {
          "id": "s042",
          "associationId": "a005",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Sp Bier bar 2",
          "people": 6
        },
        {
          "id": "s043",
          "associationId": "a006",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Wijnbar 1",
          "people": 5
        },
        {
          "id": "s044",
          "associationId": "a008",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 5",
          "people": 18
        },
        {
          "id": "s045",
          "associationId": "a008",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Cocktail 2",
          "people": 6
        },
        {
          "id": "s046",
          "associationId": "a009",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 6",
          "people": 11
        },
        {
          "id": "s047",
          "associationId": "a010",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 3 (Borrelbar)",
          "people": 15
        },
        {
          "id": "s048",
          "associationId": "a015",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Sp Bier bar 2",
          "people": 12
        },
        {
          "id": "s049",
          "associationId": "a017",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 8",
          "people": 8
        },
        {
          "id": "s050",
          "associationId": "a001",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 6",
          "people": 6
        },
        {
          "id": "s051",
          "associationId": "a025",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Sp Bier Bar 1",
          "people": 15
        },
        {
          "id": "s052",
          "associationId": "a030",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 7",
          "people": 18
        },
        {
          "id": "s053",
          "associationId": "a030",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 8",
          "people": 4
        },
        {
          "id": "s054",
          "associationId": "a031",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 4",
          "people": 40
        },
        {
          "id": "s055",
          "associationId": "a032",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Cocktail 1",
          "people": 6
        },
        {
          "id": "s056",
          "associationId": "a044",
          "day": "Zaterdag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "01:00",
          "bar": "Bar 2 (Vrijwilligersbar)",
          "people": 15
        },
        {
          "id": "s057",
          "associationId": "a007",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 6",
          "people": 18
        },
        {
          "id": "s058",
          "associationId": "a008",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 5",
          "people": 18
        },
        {
          "id": "s059",
          "associationId": "a008",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Wijnbar 1",
          "people": 5
        },
        {
          "id": "s060",
          "associationId": "a021",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 8",
          "people": 6
        },
        {
          "id": "s061",
          "associationId": "a022",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Sp Bier bar 2",
          "people": 10
        },
        {
          "id": "s062",
          "associationId": "a024",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Cocktail 2",
          "people": 6
        },
        {
          "id": "s063",
          "associationId": "a025",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Sp Bier Bar 1",
          "people": 13
        },
        {
          "id": "s064",
          "associationId": "a030",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 7",
          "people": 18
        },
        {
          "id": "s065",
          "associationId": "a030",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 8",
          "people": 4
        },
        {
          "id": "s066",
          "associationId": "a031",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 4",
          "people": 40
        },
        {
          "id": "s067",
          "associationId": "a044",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 2 (Vrijwilligersbar)",
          "people": 15
        },
        {
          "id": "s068",
          "associationId": "a045",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Sp Bier bar 2",
          "people": 8
        },
        {
          "id": "s069",
          "associationId": "a046",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Cocktail 1",
          "people": 6
        },
        {
          "id": "s070",
          "associationId": "a049",
          "day": "Zaterdag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 3 (Borrelbar)",
          "people": 15
        },
        {
          "id": "s071",
          "associationId": "a019",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "23:30",
          "bar": "Bar 8",
          "people": 6
        },
        {
          "id": "s072",
          "associationId": "a011",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Bar 5",
          "people": 18
        },
        {
          "id": "s073",
          "associationId": "a013",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Sp Bier bar 2",
          "people": 2
        },
        {
          "id": "s074",
          "associationId": "a016",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Bar 7",
          "people": 18
        },
        {
          "id": "s075",
          "associationId": "a017",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Cocktail 1",
          "people": 6
        },
        {
          "id": "s076",
          "associationId": "a020",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Cocktail 2",
          "people": 6
        },
        {
          "id": "s077",
          "associationId": "a024",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Sp Bier bar 2",
          "people": 12
        },
        {
          "id": "s078",
          "associationId": "a025",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Sp Bier Bar 1",
          "people": 15
        },
        {
          "id": "s079",
          "associationId": "a026",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Bar 6",
          "people": 15
        },
        {
          "id": "s080",
          "associationId": "a029",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Bar 3 (Borrelbar)",
          "people": 13
        },
        {
          "id": "s081",
          "associationId": "a031",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Bar 4",
          "people": 40
        },
        {
          "id": "s082",
          "associationId": "a039",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Wijnbar 1",
          "people": 4
        },
        {
          "id": "s083",
          "associationId": "a044",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "00:30",
          "bar": "Bar 2 (Vrijwilligersbar)",
          "people": 15
        },
        {
          "id": "s084",
          "associationId": "a046",
          "day": "Zondag",
          "daypart": "Avond",
          "from": "18:00",
          "to": "23:30",
          "bar": "Bar 8",
          "people": 6
        },
        {
          "id": "s085",
          "associationId": "a002",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 5",
          "people": 18
        },
        {
          "id": "s086",
          "associationId": "a007",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Sp Bier bar 2",
          "people": 18
        },
        {
          "id": "s087",
          "associationId": "a013",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 8",
          "people": 6
        },
        {
          "id": "s088",
          "associationId": "a018",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Cocktail 2",
          "people": 6
        },
        {
          "id": "s089",
          "associationId": "a001",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 6",
          "people": 4
        },
        {
          "id": "s090",
          "associationId": "a025",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Sp Bier Bar 1",
          "people": 15
        },
        {
          "id": "s091",
          "associationId": "a028",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 6",
          "people": 15
        },
        {
          "id": "s092",
          "associationId": "a031",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 4",
          "people": 40
        },
        {
          "id": "s093",
          "associationId": "a038",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Cocktail 1",
          "people": 6
        },
        {
          "id": "s094",
          "associationId": "a041",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 3 (Borrelbar)",
          "people": 18
        },
        {
          "id": "s095",
          "associationId": "a044",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 2 (Vrijwilligersbar)",
          "people": 15
        },
        {
          "id": "s096",
          "associationId": "a045",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Wijnbar 1",
          "people": 5
        },
        {
          "id": "s097",
          "associationId": "a046",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 8",
          "people": 8
        },
        {
          "id": "s098",
          "associationId": "a048",
          "day": "Zondag",
          "daypart": "Middag",
          "from": "13:00",
          "to": "18:00",
          "bar": "Bar 7",
          "people": 18
        }
      ],
      "barCaps": {
        "Bar 2 (Vrijwilligersbar)": 15,
        "Bar 3 (Borrelbar)": 15,
        "Bar 4": 40,
        "Bar 5": 18,
        "Bar 6": 18,
        "Bar 7": 18,
        "Bar 8": 12,
        "Sp Bier Bar 1": 15,
        "Sp Bier bar 2": 18,
        "Cocktail 1": 6,
        "Cocktail 2": 6,
        "Wijnbar 1": 4,
        "Wijnbar 2": 4
      }
    }
  }
};
